-- Simulacruis starts as a clone of Nauvis's own planet prototype, then
-- has its terrain-shape fields overridden below to the zone-aware
-- composites from zone-masks.lua/biome-regions.lua/property-expressions.lua.
-- Which tiles/ores/entities actually appear in each zone is handled by
-- the other terrain/*.lua files, all required after this one.
local planet = table.deepcopy(data.raw["planet"]["nauvis"])

planet.name = "simulacruis"
planet.localised_name = "Simulacruis"
-- Sorts before Nauvis's own "a[nauvis]" so Simulacruis is the first
-- planet listed on the New Game / starmap screens, since it's the
-- actual starting planet.
planet.order = "a[0-simulacruis]"

-- Procedurally composited (no art tool available in this environment):
-- a radial swirl sampling real pixels from each of the five source
-- planets' own starmap icon art, spiraling into a mixed core — crisp,
-- distinct wedges of each planet's actual terrain/lighting near the
-- rim, blending together only near the center. Meant to read at a
-- glance as "five planets combined," distinguishing Simulacruis from
-- every real planet's own icon at both the inventory-icon and starmap
-- scale. Generated by tools/generate_planet_icon.py — see that file
-- for how to regenerate (needs local copies of the 5 source PNGs,
-- which aren't shipped in this repo) or if this ever gets replaced
-- with hand-drawn art instead.
planet.icon = "__space-age-all-in-one__/graphics/icons/simulacruis.png"
planet.icon_size = 128
planet.starmap_icon = "__space-age-all-in-one__/graphics/icons/starmap-planet-simulacruis.png"
planet.starmap_icon_size = 512

-- table.deepcopy carried over Nauvis's own distance/orientation fields,
-- which PlanetsLib:extend refuses to accept directly (it derives them
-- from the orbit block below instead).
planet.distance = nil
planet.orientation = nil

planet.orbit = {
  parent = { name = "star", type = "space-location" },
  -- Same orbit ring as Nauvis (distance = 15), not Vulcanus (10) —
  -- orientation kept distinct from Nauvis's own 0.275 so the two
  -- don't sit on top of each other on the starmap.
  distance = 15,
  orientation = 0.2
}

-- Zone-aware terrain shape: each field is a weighted composite of the
-- five source planets' own fields, using the zone/biome weights from
-- zone-masks.lua and biome-regions.lua (cliffiness included — see
-- property-expressions.lua for its own per-biome composite). cliff_
-- elevation reuses the shared vanilla default, since it's a generic
-- function of elevation rather than something planet-specific.
planet.map_gen_settings.property_expression_names = {
  elevation = "simulacruis_elevation",
  aux = "simulacruis_aux",
  moisture = "simulacruis_moisture",
  temperature = "simulacruis_temperature",
  cliffiness = "simulacruis_cliffiness",
  cliff_elevation = "cliff_elevation_from_elevation"
}

PlanetsLib:extend(planet)
